use std::collections::HashMap;

/// Parse Cargo.lock — text parse `[[package]]` sections for `name` + `checksum`.
///
/// Format:
/// ```toml
/// [[package]]
/// name = "serde"
/// version = "1.0.193"
/// source = "registry+https://github.com/rust-lang/crates.io-index"
/// checksum = "25dd9975e68d0cb5aa1120c288333fc98731bd1dd12f561e468ea5c6c71b1e9b"
/// ```
pub fn parse_cargo_lock(content: &str) -> HashMap<String, String> {
    let mut versions = HashMap::new();
    let mut current_name: Option<String> = None;
    let mut current_checksum: Option<String> = None;
    let mut current_version: Option<String> = None;
    let mut in_package = false;

    for line in content.lines() {
        let trimmed = line.trim();

        if trimmed == "[[package]]" {
            // Flush previous package
            flush_cargo_package(
                &mut current_name,
                &mut current_checksum,
                &mut current_version,
                &mut versions,
            );
            in_package = true;
            continue;
        }

        if trimmed.starts_with('[') {
            flush_cargo_package(
                &mut current_name,
                &mut current_checksum,
                &mut current_version,
                &mut versions,
            );
            in_package = false;
            continue;
        }

        if !in_package {
            continue;
        }

        if let Some(val) = trimmed.strip_prefix("name = ") {
            current_name = Some(unquote(val).to_string());
        } else if let Some(val) = trimmed.strip_prefix("checksum = ") {
            current_checksum = Some(unquote(val).to_string());
        } else if let Some(val) = trimmed.strip_prefix("version = ") {
            current_version = Some(unquote(val).to_string());
        }
    }

    // Flush last package
    flush_cargo_package(
        &mut current_name,
        &mut current_checksum,
        &mut current_version,
        &mut versions,
    );

    versions
}

fn flush_cargo_package(
    name: &mut Option<String>,
    checksum: &mut Option<String>,
    version: &mut Option<String>,
    versions: &mut HashMap<String, String>,
) {
    if let Some(n) = name.take() {
        // Prefer checksum, fall back to version
        let value = checksum
            .take()
            .or_else(|| version.take())
            .unwrap_or_default();
        if !value.is_empty() {
            versions.entry(n).or_insert(value);
        }
    }
    *checksum = None;
    *version = None;
}

fn unquote(s: &str) -> &str {
    let s = s.trim();
    if (s.starts_with('"') && s.ends_with('"')) || (s.starts_with('\'') && s.ends_with('\'')) {
        &s[1..s.len() - 1]
    } else {
        s
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_parse_cargo_lock() {
        let content = r#"
# This file is automatically @generated by Cargo.
# It is not intended for manual editing.
version = 3

[[package]]
name = "serde"
version = "1.0.193"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "25dd9975e68d0cb5aa1120c288333fc98731bd1dd12f561e468ea5c6c71b1e9b"

[[package]]
name = "tokio"
version = "1.35.0"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "abc123def456"

[[package]]
name = "my-local-crate"
version = "0.1.0"
"#;
        let versions = parse_cargo_lock(content);
        assert_eq!(
            versions.get("serde").map(|s| s.as_str()),
            Some("25dd9975e68d0cb5aa1120c288333fc98731bd1dd12f561e468ea5c6c71b1e9b")
        );
        assert_eq!(
            versions.get("tokio").map(|s| s.as_str()),
            Some("abc123def456")
        );
        // Local crate without checksum should fall back to version
        assert_eq!(
            versions.get("my-local-crate").map(|s| s.as_str()),
            Some("0.1.0")
        );
    }

    #[test]
    fn test_parse_cargo_lock_empty() {
        let versions = parse_cargo_lock("version = 3\n");
        assert!(versions.is_empty());
    }
}
